# Generated by Django 6.1 on 2026-08-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_num', models.IntegerField()),
                ('site_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('county', models.CharField(max_length=200)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('height', models.FloatField()),
                ('structure', models.CharField(max_length=200)),
                ('frn_num', models.IntegerField()),
                ('faa_study_num', models.CharField(max_length=200)),
            ],
        ),
    ]
