# Generated by Django 6.1 on 2026-08-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_sites_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='address',
            new_name='address_city',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='county',
            new_name='address_county',
        ),
        migrations.AddField(
            model_name='site',
            name='address_street',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
