# Generated by Django 6.1 on 2026-08-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_address_site_address_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='address_zip',
            field=models.IntegerField(default=90210),
            preserve_default=False,
        ),
    ]
