# Generated by Django 6.1 on 2026-08-10 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_site_address_zip'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tower_photos/')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.site')),
            ],
        ),
    ]
