# Generated by Django 6.1 on 2026-08-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_sitephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='address_state',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
